config/routes.rb
Hadean::Application.routes.draw do

  resources :image_groups
  # mount Resque::Server.new, at: "/resque"

  namespace(:admin){ namespace(:customer_service){ resources :comments } }

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'admin'       => 'admin/overviews#index'
  get 'login'       => 'user_sessions#new'
  get 'logout'      => 'user_sessions#destroy'
  delete 'logout'   => 'user_sessions#destroy'
  get 'signup'      => 'customer/registrations#new'
  get 'admin/merchandise' => 'admin/merchandise/summary#index'

  resource  :about,         only: [:show]
  resources :notifications, only: [:update]
  resources :products,      only: [:index, :show, :create]
  resources :states,        only: [:index]
  resources :terms,         only: [:index]
  resource  :unsubscribe,   only: :show
  resources :wish_items,    only: [:index, :destroy]

  root :to => "welcome#index"

  namespace :customer do
    resources :registrations,   only: [:index, :new, :create]
    resource  :password_reset,  only: [:new, :create, :edit, :update]
    resource  :activation,      only: [:show]
  end

  namespace :myaccount do
    resources :orders,        only: [:index, :show]
    resources :addresses
    resources :credit_cards
    resources :referrals,     only: [:index, :create, :update]
    resource  :store_credit,  only: [:show]
    resource  :overview,      only: [:show, :edit, :update]
  end

  namespace :shopping do
    resources  :addresses do
      member do
        put :select_address
      end
    end

    resources  :billing_addresses do
      member do
        put :select_address
      end
    end

    resources  :cart_items do
      member do
        put :move_to
      end
    end
    resource  :coupon, only: [:show, :create]

    resources  :orders do
      member do
        get :checkout
        get :confirmation
      end
    end
    resources  :shipping_methods
  end

  namespace :admin do
    namespace :customer_service do
      resources :users do
        resources :comments
      end
    end
    resources :users
    namespace :user_datas do

      resources :referrals do
        member do
          post :apply
        end
      end

      resources :users do
        resource :store_credits, only: [:show, :edit, :update]
        resources :addresses
      end
    end
    resources :overviews, only: [:index]

    get "help" => "help#index"

    namespace :reports do
      resource :overview, only: [:show]
      resources :graphs
      resources :weekly_charts, only: [:index]
    end
    namespace :rma do
      resources  :orders do
        resources  :return_authorizations do
          member do
            put :complete
          end
        end
      end
      #resources  :shipments
    end

    namespace :history do
      resources  :orders, only: [:index, :show] do
        resources  :addresses, only: [:index, :show, :edit, :update, :new, :create]
      end
    end

    namespace :fulfillment do
      resources  :orders do
        member do
          put :create_shipment
        end
        resources  :comments
      end

      namespace :partial do
        resources  :orders do
          resources :shipments, only: [ :create, :new, :update ]
        end
      end

      resources  :shipments do
        member do
          put :ship
        end
        resources  :addresses , only: [:edit, :update]# This is for editing the shipment address
      end
    end
    namespace :shopping do
      resources :carts
      resources :products
      resources :users
      namespace :checkout do
        resources :billing_addresses, only: [:index, :update, :new, :create, :select_address] do
          member do
            put :select_address
          end
        end
        resources :credit_cards
        resource  :order, only: [:show, :update, :start_checkout_process] do
          member do
            post :start_checkout_process
          end
        end
        resources :shipping_addresses, only: [:index, :update, :new, :create, :select_address] do
          member do
            put :select_address
          end
        end
        resources :shipping_methods, only: [:index, :update]
      end
    end
    namespace :config do
      resources :accounts
      resources :countries, only: [:index, :edit, :update, :destroy] do
        member do
          put :activate
        end
      end
      resources :overviews
      resources :shipping_categories
      resources :shipping_rates
      resources :shipping_methods
      resources :shipping_zones
      resources :tax_rates
      resources :tax_categories
    end

    namespace :generic do
      resources :coupons
      resources :deals
      resources :sales
    end
    namespace :inventory do
      resources :suppliers
      resources :overviews
      resources :purchase_orders
      resources :receivings
      resources :adjustments
    end

    namespace :merchandise do
      namespace :images do
        resources :products
      end
      resources :image_groups
      resources :properties
      resources :prototypes
      resources :brands
      resources :product_types
      resources :prototype_properties

      namespace :changes do
        resources :products do
          resource :property,          only: [:edit, :update]
        end
      end

      namespace :wizards do
        resources :brands,              only: [:index, :create, :update]
        resources :products,            only: [:new, :create]
        resources :properties,          only: [:index, :create, :update]
        resources :prototypes,          only: [:update]
        resources :tax_categories,      only: [:index, :create, :update]
        resources :shipping_categories, only: [:index, :create, :update]
        resources :product_types,       only: [:index, :create, :update]
      end

      namespace :multi do
        resources :products do
          resource :variant,      only: [:edit, :update]
        end
      end
      resources :products do
        member do
          get :add_properties
          put :activate
        end
        resources :variants
      end
      namespace :products do
        resources :descriptions, only: [:edit, :update]
      end
    end
    namespace :document do
      resources :invoices
    end
  end

end

app/models/product_type.rb
class ProductType < ApplicationRecord
  acts_as_nested_set  #:order => "name"
  has_many :products, dependent: :restrict_with_exception

  validates :name,    presence: true, length: { :maximum => 255 }

  FEATURED_TYPE_ID = 1

  # paginated results from the admin ProductType grid
  #
  # @param [Optional params]
  # @return [ Array[ProductType] ]
  def self.admin_grid(params = {})
    grid = ProductType
    grid = grid.where("product_types.name LIKE ?", "#{params[:name]}%")              if params[:name].present?
    grid
  end

end

app/controllers/admin/merchandise/images/products_controller.rb
class Admin::Merchandise::Images::ProductsController < Admin::BaseController

  def edit
    @product  = Product.includes(:images).friendly.find(params[:id])
  end

  def update
    @product  = Product.friendly.find(params[:id])

    if @product.update_attributes(allowed_params)
      redirect_to action: :edit
    else
      render action: :edit
    end
  end

  def show
    @product = Product.friendly.includes(:images).find(params[:id])
  end
  private

  def allowed_params
    params.require(:product).permit!
  end

end

app/controllers/admin/merchandise/products/descriptions_controller.rb
class Admin::Merchandise::Products::DescriptionsController < Admin::BaseController
  def edit
    @product = Product.friendly.find(params[:id])
  end

  def update
    @product = Product.friendly.find(params[:id])
    if @product.update_attributes(allowed_params)
      redirect_to admin_merchandise_product_url(@product)
    else
      render :action => :edit
    end
  end
  private

  def allowed_params
    params.require(:product).permit(:name, :description_markup)
  end
end

app/controllers/admin/merchandise/products_controller.rb
class Admin::Merchandise::ProductsController < Admin::BaseController
  helper_method :sort_column, :sort_direction, :product_types
  authorize_resource

  def index
    params[:page] ||= 1
    @products = Product.admin_grid(params).order(sort_column + " " + sort_direction).
                                              paginate(page: pagination_page, per_page: pagination_rows)
  end

  def show
    @product        = Product.friendly.find(params[:id])
    @shipping_zones =  ShippingZone.all
    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

  def new
    form_info
    if @prototypes.empty?
      flash[:notice] = "You must create a prototype before you create a product."
      redirect_to new_admin_merchandise_prototype_url
    else
      @product            = Product.new
      @product.prototype  = Prototype.new
    end
  end

  def create
    @product = Product.new(allowed_params)

    if @product.save
      flash[:notice] = "Success, You should create a variant for the product."
      redirect_to edit_admin_merchandise_products_description_url(@product)
    else
      form_info
      flash[:error] = "The product could not be saved"
      render action: :new
    end
  rescue
    render :text => "Please make sure you have solr started... Run this in the command line => bundle exec rake sunspot:solr:start"
  end

  def edit
    @product        = Product.friendly.includes(:properties,:product_properties, {:prototype => :properties}).find(params[:id])
    form_info
  end

  def update
    @product = Product.friendly.find(params[:id])

    if @product.update_attributes(allowed_params)
      redirect_to admin_merchandise_product_url(@product)
    else
      form_info
      render action: :edit#, :layout => 'admin_markup'
    end
  end

  def add_properties
    prototype  = Prototype.friendly.includes(:properties).find(params[:id])
    @properties = prototype.properties
    all_properties = Property.all

    @properties_hash = all_properties.inject({:active => [], :inactive => []}) do |h, property|
      if  @properties.detect{|p| (p.id == property.id) }
        h[:active] << property.id
      else
        h[:inactive] << property.id
      end
      h
    end
    respond_to do |format|
      format.html
      format.json { render json: @properties_hash.to_json }
    end
  end

  def activate
    @product = Product.friendly.find(params[:id])
    @product.deleted_at = nil
    if @product.save
      redirect_to admin_merchandise_product_url(@product)
    else
      if @product.description.blank?
        flash[:alert] = "Please add a description before Activating."
      else
        flash[:alert] = @product.errors.full_messages.join('  ')
      end
      redirect_to edit_admin_merchandise_products_description_url(@product)
    end
  end

  def destroy
    @product = Product.friendly.find(params[:id])
    @product.deleted_at ||= Time.zone.now
    @product.save

    redirect_to admin_merchandise_product_url(@product)
  end

  private

    def allowed_params
      params.require(:product).permit(:name, :description, :product_keywords, :set_keywords, :product_type_id,
                                      :prototype_id, :shipping_category_id, :permalink, :available_at, :deleted_at,
                                      :meta_keywords, :meta_description, :featured, :description_markup, :brand_id,
                                      product_properties_attributes: [:id, :product_id, :property_id, :position, :description])
    end

    def form_info
      @prototypes               = Prototype.all.map{|pt| [pt.name, pt.id]}
      @all_properties           = Property.all
      @select_shipping_category = ShippingCategory.all.map {|sc| [sc.name, sc.id]}
      @brands                   = Brand.order(:name).map {|ts| [ts.name, ts.id]}
    end

    def product_types
      @product_types ||= ProductType.all
    end

    def sort_column
      Product.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

end

app/controllers/admin/merchandise/wizards/products_controller.rb
class Admin::Merchandise::Wizards::ProductsController < Admin::Merchandise::Wizards::BaseController
  def new
    if f = next_wizard_form
      redirect_to f
    else
      form_info
      @product = Product.new
      @product.brand_id         = session[:product_wizard][:brand_id]
      @product.product_type_id  = session[:product_wizard][:product_type_id]

      @product.shipping_category_id = session[:product_wizard][:shipping_category_id]
    end
  end

  def create
    @product = Product.new(allowed_params)
    if @product.save
      reset_product_wizard
      flash[:notice] = "Successfully created product."
      redirect_to edit_admin_merchandise_products_description_url(@product)
    else
      form_info
      render :action => 'new'
    end
  end

  private

  def allowed_params
    params.require(:product).permit(:name, :description, :product_keywords, :set_keywords, :product_type_id, :prototype_id, :shipping_category_id, :permalink, :available_at, :deleted_at, :meta_keywords, :meta_description, :featured, :description_markup, :brand_id)
  end

  def form_info
    if session[:product_wizard][:prototype_id]
      @all_properties           = Prototype.find(session[:product_wizard][:prototype_id]).properties
    else #@all_properties           = Property.all
      @all_properties           = Property.find(session[:product_wizard][:property_ids])
    end
    @select_product_types     = ProductType.all.collect{|pt| [pt.name, pt.id]}
    @select_shipping_category = ShippingCategory.all.collect {|sc| [sc.name, sc.id]}
    @brands        = Brand.order(:name).collect {|ts| [ts.name, ts.id]}
  end
end

app/controllers/admin/shopping/products_controller.rb
class Admin::Shopping::ProductsController < Admin::Shopping::BaseController
  helper_method :sort_column, :sort_direction, :product_types

  # GET /admin/order/products
  def index
    @products = Product.admin_grid(params, true).order(sort_column + " " + sort_direction).
                                              paginate(:page => pagination_page, :per_page => pagination_rows)
  end

  # GET /admin/order/products/1
  # GET /admin/order/products/1.xml
  def show
    @product = Product.friendly.includes({:variants => {:variant_properties => :property} }).find(params[:id])
  end

  def edit
    @product = Product.friendly.includes({:variants => {:variant_properties => :property} }).find(params[:id])
  end

  # PUT /admin/order/products/1
  def update
    params[:variant].each_pair do |variant_id, qty|
      if (qty.first.blank? || (!qty.first.blank? && qty.first.to_i == 0))
        session_admin_cart.remove_variant(variant_id)
      else
        session_admin_cart.add_variant(variant_id, session_admin_cart.customer, qty, ItemType::SHOPPING_CART_ID, true)
      end
    end
    respond_to do |format|
      format.html { redirect_to(admin_shopping_products_url, :notice => 'Successfully added.  Ask the customer if they would like anything else.') }
    end
  end

  private

  def product_types
    @product_types ||= ProductType.all
  end
  def sort_column
    Product.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
 # def tax_percentage(tax_rate)
 #   tax_rate ? tax_rate.rate : 0
 # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    products = Product.active.includes(:variants)

    product_types = nil
    if params[:product_type_id].present? && product_type = ProductType.find_by_id(params[:product_type_id])
      product_types = product_type.self_and_descendants.map(&:id)
    end
    if product_types
      @products = products.where(product_type_id: product_types).
                           paginate(page: pagination_page, per_page: pagination_rows)
    else
      @products = products.paginate(page: pagination_page, per_page: pagination_rows)
    end
  end

  def create
    if params[:q] && params[:q].present?
      @products = Product.standard_search(params[:q]).results
    else
      @products = Product.where('deleted_at IS NULL OR deleted_at > ?', Time.zone.now )
    end

    render :template => '/products/index'
  end

  def show
    @product = Product.friendly.active.find(params[:id])
    form_info
    @cart_item.variant_id = @product.active_variants.first.try(:id)
  end

  private

  def form_info
    @cart_item = CartItem.new
  end

  def featured_product_types
    [ProductType::FEATURED_TYPE_ID]
  end

  def pagination_rows
    params[:rows] ||= 60
    params[:rows].to_i
  end
end

app/views/admin/merchandise/images/products/_form.html.erb
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited the images from being saved:</h2>
    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div>
  <div id="product_images">
    <%= new_child_fields_template form, :images, :form_builder_local => :image_form %>
    <% @product.images.each do |image| %>
      <div id='image_<%= image.id %>'  style='padding-bottom:10px;'>
        <%= form.fields_for :images, image do |image_form|%>
          <%= render partial: 'image', locals: { image_form: image_form } %>
        <% end %>
      </div>
    <% end %>
  </div>
  <strong><%= add_child_button "New Image", :images, 'float-right small' %></strong>
</div>

app/views/admin/merchandise/images/products/_form.html.haml
- if @product.errors.any?
  #error_explanation
    %h2
      = pluralize(@product.errors.count, "error")
      prohibited this purchase_order from being saved:
    %ul
      - @product.errors.full_messages.each do |msg|
        %li= msg
%fieldset
  %legend
    Images - #{add_child_link "New Image", :images}
  = new_child_fields_template form, :images, :form_builder_local => :image_form
  #product_images.span-16
    - @product.images.each do |image|
      .variant_form.left.span-16.last{:id => "image_#{image.id}"}
        = form.fields_for :images, image do |image_form|
          = render :partial => 'image', :locals => {:image_form => image_form }

app/views/admin/merchandise/images/products/_image.html.erb
<fieldset class='row <%=  image_form.object.new_record? ? "new_fields" : "fields" %>'>
  <% if !image_form.object.new_record? %>
    <div class='large-4 column'>
      <%= image_tag image_form.object.photo.url(:small) %>
    </div>
  <% end %>
  <div class='large-8 column'>
    <div style='float:right;'>
      <%= remove_child_link('remove', image_form) %>
    </div>
    <label>Position</label>
    <%= image_form.select       :position, [1,2,3,4,5,6] %>

    <label>Caption</label>
    <%= image_form.text_field   :caption %>

    <label>Photo</label>
    <%= image_form.file_field   :photo %>

    <label>Link to image</label>
    <%= image_form.text_field   :photo_from_link %>
  </div>
</fieldset>

app/views/admin/merchandise/images/products/_image.html.haml
%fieldset{:class => image_form.object.new_record? ? "new_fields" : "fields"}
  - if !image_form.object.new_record?
    = image_tag image_form.object.photo.url(:small)
  %div{:style => "float:right;"}
    = remove_child_link('remove', image_form)
  %label Position
  = image_form.select       :position, [1,2,3,4,5,6]
  %label Caption
  = image_form.text_field   :caption
  %label Photo
  = image_form.file_field   :photo
  %label Link to image
  = image_form.text_field   :photo_from_link

app/views/admin/merchandise/images/products/edit.html.erb
<%= render :partial => '/admin/merchandise/sub_header'%>

<h3>Add Product Images</h3>

<div style='margin-bottom:10px;'>
  <strong><%= @product.name.possessive %> Images</strong>
</div>

<%= form_for @product, url: admin_merchandise_images_product_path(@product), multipart: true do |form| %>
  <%= render partial: '/admin/merchandise/images/products/form', locals: { form: form } %>
  <%= submit_tag "Create", class: "button small" %>
<% end %>

<%= link_to 'View Images', admin_merchandise_images_product_path(@product), class: "button small secondary"%>
<%= link_to 'Product Details', admin_merchandise_product_path(@product),    class: "button small secondary" %>

app/views/admin/merchandise/images/products/edit.html.haml
= render :partial => '/admin/merchandise/sub_header'
%h3 Add Product Images
= form_for @product, :url  => admin_merchandise_images_product_path(@product), :multipart => true do |form|
  = render :partial => '/admin/merchandise/images/products/form', :locals => {:form => form}
  = submit_tag "Create", :class  => "button"
= link_to 'View Images', admin_merchandise_images_product_path(@product), :class  => "button"
= link_to 'Product Details', admin_merchandise_product_path(@product), :class  => "button"

app/views/admin/merchandise/images/products/show.html.erb
<%= render partial: '/admin/merchandise/sub_header'%>

<h3>Images for '<%= @product.name %>'</h3>

<% @product.images.each do |image| %>
  <label><%= image.photo_file_name %></label>
  <%= image_tag image.photo.url(:small) %>
<% end %>

<p style="margin-top: 30px">
  <%= link_to 'Edit Images', edit_admin_merchandise_images_product_path(@product), class: "button"%>
  <%= link_to 'Product Details', admin_merchandise_product_path(@product), class: "button"%>
</p>

app/views/admin/merchandise/images/products/show.html.haml
= render :partial => '/admin/merchandise/sub_header'
%h3
  Images for '#{@product.name}'
- @product.images.each do |image|
  %label= image.photo_file_name
  = image_tag image.photo.url(:small)
%p{:style => "margin-top: 30px"}
  = link_to 'Edit Images', edit_admin_merchandise_images_product_path(@product), :class  => "button"
  = link_to 'Product Details', admin_merchandise_product_path(@product), :class  => "button"